--- a/.github/workflows/test_windows.yml
+++ b/.github/workflows/test_windows.yml
@@ -1,12 +1,8 @@
 name: Test (Windows)
 on:
   push:
-    # TODO: Also run the tests when a Windows-specific features is changed.
-    # For example, the Windows Exporter for Prometheus and Event Log tailers.
     branches:
       - main
-  # TODO: Run the Windows tests for each PR?
-  # For now we don't do it just because it takes time.
   pull_request:
     types: [labeled, opened, synchronize, reopened]
 
@@ -27,9 +23,7 @@
       uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
       with:
         go-version-file: go.mod
-        # TODO: Enable caching later.
-        # We'll need to make sure the same cache is reused by the workflow to build Windows binaries.
         cache: false
     - name: Test
       run: '& "C:/Program Files/git/bin/bash.exe" -c ''go test -tags="nodocker,nonetwork"
-        ./...'''
+        ./...'''